NANOPBDIR = $(PWD)/nanopb
GENOUTDIR = $(PWD)/Gen
NANOPB_CORE_SRC = 	$(NANOPBDIR)/pb_encode.c \
			  		$(NANOPBDIR)/pb_decode.c \
			  		$(NANOPBDIR)/pb_common.c
NANOPB_CORE_INC = $(NANOPBDIR)
NANOPB_GEN_INC = $(GENOUTDIR)
NANOPB_GEN_SRC = $(GENOUTDIR)/messages.pb.c

ALLCSRC += $(NANOPB_CORE_SRC)
ALLCSRC += $(NANOPB_GEN_SRC)

ALLINC += $(NANOPB_CORE_INC)
ALLINC += $(NANOPB_GEN_INC)