# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: messages.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class MessageID(betterproto.Enum):
    Message1ID = 0
    Message2ID = 1
    Message3ID = 2


@dataclass
class Message1(betterproto.Message):
    id: "MessageID" = betterproto.enum_field(1)
    intvalue: int = betterproto.int32_field(2)


@dataclass
class Message2(betterproto.Message):
    id: "MessageID" = betterproto.enum_field(1)
    intvalue: int = betterproto.int32_field(2)
    strvalue: str = betterproto.string_field(3)


@dataclass
class Message3(betterproto.Message):
    id: "MessageID" = betterproto.enum_field(1)
    boolvalue: bool = betterproto.bool_field(2)
